import {
  BadgeCheck,
  BriefcaseBusiness,
  Handshake,
  ScanSearch,
} from "lucide-react";
import type {
  BuyerIntent,
  CapabilityAsset,
  MatchSignal,
  NavItem,
  OpportunityTemplate,
  Subscription,
} from "./types";

export const navItems: NavItem[] = [
  { id: "discover", label: "发现", icon: ScanSearch },
  { id: "assets", label: "资产", icon: BadgeCheck },
  { id: "subscriptions", label: "订阅", icon: Handshake },
  { id: "buyers", label: "买家", icon: BriefcaseBusiness },
];

export const capabilityAssets: CapabilityAsset[] = [
  {
    id: 1,
    type: "Document / Report",
    title: "AI 出海增长审计报告包",
    seller: "Lina OPC Studio",
    handle: "0x9F...b21A",
    summary: "面向独立站和 AI SaaS 的增长漏斗审计模板、广告账户检查表和邮件序列拆解报告。",
    preview: "开放摘要、目录、样例页和最近一次更新说明；正文仅对活跃订阅者可见。",
    proof: "Verified OPC / v1.4 hash / 37 次订阅",
    price: "18 MON",
    duration: "30 days",
    currentVersion: "v1.4",
    updateFrequency: "每两周更新",
    productionMode: "AI-assisted",
    rating: 4.9,
    subscriptions: 37,
    match: 96,
    tags: ["Growth", "Report", "DTC"],
  },
  {
    id: 2,
    type: "Template / Methodology",
    title: "Monad 生态 BD 知识库",
    seller: "Mu Research Cell",
    handle: "0x72...09Dc",
    summary: "结构化项目图谱、联系人分层、会议脚本和跟进节奏，适合新团队冷启动合作网络。",
    preview: "开放 6 个样例条目和一页合作触达脚本；完整数据库按订阅访问。",
    proof: "Portfolio sample approved / v2.1 hash",
    price: "9 MON",
    duration: "14 days",
    currentVersion: "v2.1",
    updateFrequency: "每周更新",
    productionMode: "Human-authored",
    rating: 4.8,
    subscriptions: 21,
    match: 91,
    tags: ["BD", "Template", "Monad"],
  },
  {
    id: 3,
    type: "Dataset / Annotation",
    title: "中文 AI Agent 评测集",
    seller: "TinyBench OPC",
    handle: "0x31...8E4f",
    summary: "1,200 条业务任务样本，覆盖销售、客服、投研、运营，带 rubric 和基线结果。",
    preview: "开放 20 条样例任务、字段说明和 rubric 摘要；完整数据包订阅后下载。",
    proof: "CID + annotation hash + v0.9",
    price: "26 MON",
    duration: "30 days",
    currentVersion: "v0.9",
    updateFrequency: "每月更新",
    productionMode: "Agent-executed",
    rating: 4.7,
    subscriptions: 14,
    match: 88,
    tags: ["Dataset", "Eval", "Chinese"],
  },
  {
    id: 4,
    type: "Template / Methodology",
    title: "独立开发者冷启动 GTM 方法论",
    seller: "Solo GTM Lab",
    handle: "0xA4...77F0",
    summary: "12 类社群渠道筛选法、落地页 copy 模板、反馈采样表和复盘结构。",
    preview: "开放一份渠道评分表和落地页标题样例；完整模板订阅后可访问。",
    proof: "Verified OPC / structured feedback 4.6",
    price: "14 MON",
    duration: "21 days",
    currentVersion: "v1.2",
    updateFrequency: "每月更新",
    productionMode: "AI-assisted",
    rating: 4.6,
    subscriptions: 19,
    match: 84,
    tags: ["GTM", "Template", "OPC"],
  },
];

export const buyerIntents: BuyerIntent[] = [
  {
    id: 101,
    buyer: "AgentFi Builder",
    title: "寻找中文 Agent 产品冷启动知识包",
    budget: "20 MON",
    category: "Document / Report",
    need: "希望订阅一份可直接复用的增长审计报告包，先验证前 100 个高意向用户路径。",
    matchAssetId: 1,
  },
  {
    id: 102,
    buyer: "Monad Mini App Team",
    title: "寻找可信生态 BD 数据和脚本",
    budget: "10 MON",
    category: "Template / Methodology",
    need: "需要验证合作对象、邮件模板、Twitter/Telegram 触达脚本，并能看到更新版本记录。",
    matchAssetId: 2,
  },
  {
    id: 103,
    buyer: "LLM Ops Studio",
    title: "订阅中文业务任务评测样本",
    budget: "30 MON",
    category: "Dataset / Annotation",
    need: "希望先看样例任务和 rubric，再订阅完整数据包并保留链上购买记录。",
    matchAssetId: 3,
  },
];

export const opportunityTemplates: OpportunityTemplate[] = [
  {
    id: "web3-china-entry",
    title: "Monad 生态项目进入中国 / 上海市场",
    buyer: "Overseas Monad Builder",
    market: "中国 / 上海 / 华语 Web3 社区",
    budget: "20 MON",
    cycle: "4-6 weeks",
    summary:
      "需要快速理解华语社区、上海 Builder / VC / KOL 网络，并准备冷启动内容与 BD 节奏。",
    capabilities: ["BD", "Growth", "Monad", "GTM"],
    recommendedAssetId: 2,
  },
  {
    id: "ai-growth",
    title: "AI SaaS 冷启动增长诊断",
    buyer: "Solo AI Founder",
    market: "独立站 / Product Hunt / 社群渠道",
    budget: "18 MON",
    cycle: "2 weeks",
    summary:
      "需要把早期流量、广告账户、邮件序列和用户反馈整理成下一轮增长实验。",
    capabilities: ["Growth", "Report", "DTC"],
    recommendedAssetId: 1,
  },
  {
    id: "agent-eval",
    title: "企业 Agent 评测数据采购",
    buyer: "LLM Ops Studio",
    market: "中文业务场景",
    budget: "30 MON",
    cycle: "30 days",
    summary:
      "需要带 rubric 的中文业务任务样本，用于比较客服、销售、投研和运营 Agent 的执行质量。",
    capabilities: ["Dataset", "Eval", "Chinese"],
    recommendedAssetId: 3,
  },
];

export const matchSignals: MatchSignal[] = [
  {
    assetId: 1,
    score: 96,
    reason: "覆盖增长审计、广告账户检查、邮件序列和 DTC 漏斗，适合 AI SaaS 冷启动。",
    trust: "Verified OPC、37 次订阅、v1.4 版本 hash 和结构化反馈记录。",
    risk: "报告包不能替代实际投放执行，买家仍需自行接入广告账户和分析工具。",
    suggestion: "先订阅 30 天，用免费样例确认字段，再把增长实验摘要写入采购记录。",
    intentSummary:
      "Buyer subscribes to AI growth audit report v1.4 for growth diagnosis and feedback-backed reputation.",
  },
  {
    assetId: 2,
    score: 91,
    reason: "包含 Monad 生态项目图谱、联系人分层、会议脚本和触达节奏，贴合中国 / 上海市场进入。",
    trust: "Portfolio sample approved、v2.1 版本 hash、21 次订阅和人工维护更新频率。",
    risk: "联系人图谱会快速过期，订阅价值依赖持续更新和买家自身执行速度。",
    suggestion: "先订阅 14 天，把 BD 触达脚本和目标名单作为第一阶段采购资产。",
    intentSummary:
      "Buyer subscribes to Monad BD knowledge base v2.1 for China market entry and records access proof.",
  },
  {
    assetId: 3,
    score: 88,
    reason: "提供 1,200 条中文业务任务样本、rubric 和基线结果，适合 Agent 评测。",
    trust: "CID、annotation hash、Agent-executed 生产方式披露和 v0.9 数据版本。",
    risk: "数据集无法保证覆盖所有行业，需要买家按任务类型抽样复核。",
    suggestion: "订阅后先运行 20 条样例任务，对 rubric 适配性提交结构化反馈。",
    intentSummary:
      "Buyer subscribes to Chinese agent evaluation dataset v0.9 and records dataset access hash.",
  },
  {
    assetId: 4,
    score: 84,
    reason: "覆盖冷启动渠道评分、落地页 copy 和复盘结构，适合独立开发者 GTM。",
    trust: "Verified OPC、v1.2 模板版本、结构化反馈评分 4.6。",
    risk: "模板不能直接保证获客结果，需要买家按自身产品定位调整。",
    suggestion: "将渠道评分表作为第一周计划，订阅期内持续取用更新模板。",
    intentSummary:
      "Buyer subscribes to solo founder GTM methodology v1.2 for channel scoring and launch planning.",
  },
];

export const initialSubscriptions: Subscription[] = [
  {
    id: "S-2401",
    assetId: 1,
    title: "AI 出海增长审计报告包",
    buyer: "AgentFi Builder",
    seller: "Lina OPC Studio",
    value: "18 MON",
    status: "Feedback",
    evidence: "feedback-hash:0x91cf...2ad0",
  },
  {
    id: "S-2398",
    assetId: 2,
    title: "Monad 生态 BD 知识库",
    buyer: "Monad Mini App Team",
    seller: "Mu Research Cell",
    value: "9 MON",
    status: "Released",
    evidence: "version-hash:0x4db1...92aa",
  },
  {
    id: "S-2394",
    assetId: 4,
    title: "独立开发者冷启动 GTM 方法论",
    buyer: "Solo SaaS Founder",
    seller: "Solo GTM Lab",
    value: "14 MON",
    status: "Subscribed",
    evidence: "access-hash:0x7a21...",
  },
];
